//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFIDTagType
    {
        public RFIDTagType()
        {
            this.RFIDTags = new HashSet<RFIDTag>();
        }
    
        public int RFIDTagTypeID { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<RFIDTag> RFIDTags { get; set; }
    }
}
