//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionID { get; set; }
        public int userID { get; set; }
        public int bookID { get; set; }
        public System.DateTime borrowDate { get; set; }
        public System.DateTime expectedReturn { get; set; }
        public int status { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual TransactionStatu TransactionStatu { get; set; }
        public virtual User User { get; set; }
    }
}
