//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Writer
    {
        public Writer()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int writerID { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
